# Generated by Django 4.1.7 on 2023-03-26 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('is_moderator', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('tag', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.IntegerField(blank=True, default=1000)),
                ('gatekeep_access', models.BooleanField(blank=True, default=False)),
                ('access_password', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('player', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTemporary',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.useraccount')),
                ('temporary_password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('patch_id', models.CharField(max_length=10)),
                ('finalized', models.BooleanField(blank=True, default=False)),
                ('players', models.ManyToManyField(blank=True, related_name='played_sessions', to='base.player')),
                ('session_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.useraccount')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_sessions', to='base.player')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.PositiveSmallIntegerField()),
                ('outcome', models.CharField(blank=True, default='', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.session')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.player')),
            ],
            options={
                'unique_together': {('session', 'round_id')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_players', to='base.useraccount'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=32)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('payload', models.CharField(max_length=150)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.round')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'name', 'tag')},
        ),
        migrations.CreateModel(
            name='AccessGranted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessed_by', to='base.useraccount')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_access', to='base.useraccount')),
            ],
            options={
                'unique_together': {('user_from', 'user_to')},
            },
        ),
    ]
